export const LOAD_CART = 'LOAD_CART';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CHANGE_FREIGHT = 'CHANGE_FREIGHT';
export const CHANGE_NOTE = 'CHANGE_NOTE';
export const CHANGE_PAYMENT_TYPE = 'CHANGE_PAYMENT_TYPE';
export const RESET_SHOPPING_CART = 'RESET_SHOPPING_CART';